### ISSUE TITLE
Unable to get better resolution of images for PhotoCollage.py

### ISSUE THREAD

**Issue by juanscanlan** [twilsonco/PyPhotoCollage#3]
First of, I really appreciate the work yo have done. It works great.
The only issue I have is with the resolution.
I have tried setting the image sizes in the arguments to very large values, but nothing seems to increase the resolution of the images in the collage. Delimitry's collage_maker produced a higher quality image.

**Comment by twilsonco** [comment]
Thanks Juan. The problem was that, despite the user options, images need to have the same height in order to the algorithm to work, and they were being downscaled to match the minimum image height. Instead they are now upscaled to match the maximum image height. 

The output size of the collage is still limited by the resolution of the input images; that is, it won't upscale _every_ image. But now you should be able to freely specify a _lower_ width or height than what the input-image-determined maximum resolution would be.

Give it another shot and let me know if it works.

**Comment by juanscanlan** [comment]
It works great! The images are of much higher quality. I really appreciate your response and improvement on the code. I really think its the best algorithm out there, even outside python.
